chess_api:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: chess_api
  command: uv run python3 src/manage.py runserver ${API_HOST}:${API_PORT:-8000}
  volumes:
    - .:/app
  ports:
    - "${API_PORT:-8000}:${API_PORT:-8000}"
  env_file:
    - .env
  depends_on:
    - university_schedule_db